#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Get version from argument, default to 1.0.0 if not provided
VERSION=${1:-1.0.0}

echo "Starting build process for version $VERSION..."

# 1. Run npm run build
echo "Running npm run build..."
npm run build

# 2. Run npm run build:legacy
# echo "Running npm run build:legacy..."
# npm run build:legacy

# 3. Run npm run makepot
echo "Running npm run makepot..."
npm run makepot

# 3b. Build the per-handle JSON translation files.
# wp_set_script_translations() (BlockManager.php, Admin.php) loads
# tubebay-<locale>-<md5>.json, which only make-json produces. Without this the
# zip ships a .pot containing the block strings and no JSON for the editor to
# read, so those strings stay untranslated at runtime.
echo "Running npm run make-json..."
npm run make-json



# # 3. Rename license file
# echo "Renaming license file..."
# if [ -f "build/admin-legacy.js.LICENSE.txt" ]; then
#     mv build/admin-legacy.js.LICENSE.txt build/admin.js.LICENSE.txt
#     echo "Renamed build/admin-legacy.js.LICENSE.txt to build/admin.js.LICENSE.txt"
# else
#     echo "Warning: build/admin-legacy.js.LICENSE.txt not found. Skipping rename."
# fi

# 4. Add headers
HEADER="/*
 * TubeBay
 * Copyright (c) $(date +%Y) WPAnchorBay - wpanchorbay.com
 *
 * This software is licensed under the GPLv2 or later.
 * This file is generated from un-compiled source code. Do not edit this file directly.
 *
 * Source Code (Root): https://github.com/wpanchorbay/tubebay/tree/$VERSION/
 * Source Code (Admin): https://github.com/wpanchorbay/tubebay/tree/$VERSION/src
 *
 */"

# List of files to edit.
# Block AND format bundles are included alongside the admin bundle: all of them
# are minified generated output shipped to wp.org, so they carry the same
# source-disclosure header. nullglob keeps the loop quiet if a given group
# hasn't been built.
shopt -s nullglob
FILES=("build/admin.js" build/blocks/*/index.js build/formats/*/index.js)
shopt -u nullglob

# Loop through each file and prepend the header
for file in "${FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "Adding header to $file..."
        echo "$HEADER" | cat - "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
        echo "Successfully added header to $file"
    else
        echo "Warning: File $file not found."
    fi
done

echo "Build and header addition complete for version $VERSION."
